# Welcome to Jekyll!

# Website settings
title: "邸佳松"
description: "Baron's blog,use Jekyll and github pages."
keywords: "Baron,Trail,blog,Jekyll,github,gh-pages"

baseurl: "/"
url: "http://barondi.github.io"
# url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: '邸佳松'
  first_name: 'Di'
  last_name: 'Baron'
  email: '15011077963@163.com'
  facebook_username: 'jiakunnj'
  github_username: 'barondi'
  head_img: 'static/img/landing/baron.jpg'

# social link
jingyu:
  first_name: 'Net'
  last_name: 'Imooc'
  description: 'FE Studying.'
  link: 'http://www.imooc.com/'
  email: '15011077963@163.com'
jingyu2:
  first_name: 'Net'
  last_name: 'W3cplus'
  description: 'FE Studying.'
  link: 'http://www.w3cplus.com/'
  email: '15011077963@163.com'
jingyu3:
  first_name: 'Net'
  last_name: '51cto'
  description: 'FE Studying.'
  link: 'http://www.51cto.com/'
  email: '15011077963@163.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
